export const uiCopy = {
  en: {
    navigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    footerNavigation: "Footer navigation",
    home: "Home",
    about: "About Us",
    products: "Products",
    solutions: "Solutions",
    service: "Service & Support",
    resources: "Resources",
    contact: "Contact",
    requestQuote: "Request Quote",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    language: "Language",
    productsOptical: "Super Optical Sorting System",
    productsConstruction: "Construction and Bulky Waste Line",
    caseStudies: "Case Studies",
    processIntegration: "Process Integration",
    supportModules: "Support Modules",
    supportPath: "Support Path",
    workingMethod: "Working Method",
    buyerValue: "Buyer Value",
    resourceLibrary: "Resource Library",
    rfqPreparation: "RFQ Preparation",
    teamUse: "How Teams Use Them",
    faq: "FAQ",
    guideRoadmap: "Guide roadmap",
    companyFoundation: "Company Foundation",
    capabilitySystem: "Capability System",
    credentials: "Credentials",
    evidenceGallery: "Evidence Gallery",
    news: "News",
    projectConsultation: "Project Consultation",
    nextSteps: "What Happens Next",
    inquiryChecklist: "Inquiry Checklist",
    socialNavigation: "Social media links",
    followInstagram: "Follow WEI LAN on Instagram",
    followLinkedIn: "Follow WEI LAN on LinkedIn",
    followX: "Follow WEI LAN on X",
    followYouTube: "Follow WEI LAN on YouTube",
    organizationDescription: "Environmental equipment manufacturer focused on intelligent waste sorting and resource recovery systems.",
    contactFeedback: {
      PRODUCT_REQUIRED: "Please choose a product line.",
      NAME_REQUIRED: "Name is required.",
      EMAIL_REQUIRED: "Email is required.",
      EMAIL_INVALID: "Enter a valid email address.",
      MESSAGE_REQUIRED: "Project details are required.",
      FIELD_TOO_LONG: "One or more fields are too long.",
      INVALID_REQUEST: "Check the form details and try again.",
      DELIVERY_FAILED: "Unable to send your inquiry right now. Please try again.",
      INTERNAL_ERROR: "Inquiry submission failed. Please try again.",
      sending: "Sending your inquiry...",
      success: "Inquiry sent. Our sales team will contact you soon.",
      generic: "Inquiry submission failed. Please try again.",
      chooseProduct: "Choose product line",
      wasteDisabled: "Select product line first",
      wastePlaceholder: "Select waste types",
      clear: "Clear",
      all: "All",
      empty: "Select a product line to view waste type suggestions.",
      wasteTypes: {},
      resourceUnlock: {
        sending: "Unlocking resources...",
        generic: "Unable to unlock resources right now. Please try again.",
        prefill: "I would like to receive more WEI LAN resource materials.",
        errors: {
          INVALID_REQUEST: "Check the form details and try again.",
          INVALID_ORIGIN: "Unable to unlock resources from this page.",
          INVALID_RESOURCE: "This resource request is invalid.",
          NAME_REQUIRED: "Name is required.",
          EMAIL_REQUIRED: "Work email is required.",
          EMAIL_INVALID: "Enter a valid work email address.",
          COMPANY_REQUIRED: "Company is required.",
          FIELD_TOO_LONG: "One or more fields are too long.",
          DELIVERY_FAILED: "Unable to unlock resources right now. Please try again.",
        },
      },
    },
  },
  "zh-CN": {
    navigation: "主导航",
    mobileNavigation: "移动端导航",
    footerNavigation: "页脚导航",
    home: "首页",
    about: "关于我们",
    products: "产品中心",
    solutions: "解决方案",
    service: "服务与支持",
    resources: "资料中心",
    contact: "联系我们",
    requestQuote: "获取报价",
    openNavigation: "打开导航",
    closeNavigation: "关闭导航",
    language: "语言",
    productsOptical: "超级光选系统",
    productsConstruction: "建筑与大件垃圾处理线",
    caseStudies: "项目案例",
    processIntegration: "工艺集成",
    supportModules: "支持模块",
    supportPath: "服务路径",
    workingMethod: "合作方式",
    buyerValue: "客户价值",
    resourceLibrary: "资料库",
    rfqPreparation: "询价准备",
    teamUse: "团队使用方式",
    faq: "常见问题",
    guideRoadmap: "指南规划",
    companyFoundation: "企业基础",
    capabilitySystem: "能力体系",
    credentials: "资质认证",
    evidenceGallery: "实力展示",
    news: "新闻动态",
    projectConsultation: "项目咨询",
    nextSteps: "后续流程",
    inquiryChecklist: "咨询清单",
    socialNavigation: "社交媒体链接",
    followInstagram: "在 Instagram 关注 WEI LAN",
    followLinkedIn: "在 LinkedIn 关注 WEI LAN",
    followX: "在 X 关注 WEI LAN",
    followYouTube: "在 YouTube 关注 WEI LAN",
    organizationDescription: "专注于智能废弃物分选与资源回收系统的环保装备制造商。",
    contactFeedback: {
      PRODUCT_REQUIRED: "请选择产品线。",
      NAME_REQUIRED: "请输入姓名。",
      EMAIL_REQUIRED: "请输入电子邮箱。",
      EMAIL_INVALID: "请输入有效的电子邮箱地址。",
      MESSAGE_REQUIRED: "请输入项目详情。",
      FIELD_TOO_LONG: "一个或多个字段内容过长。",
      INVALID_REQUEST: "请检查表单信息后重试。",
      DELIVERY_FAILED: "暂时无法发送咨询，请稍后重试。",
      INTERNAL_ERROR: "咨询提交失败，请稍后重试。",
      sending: "正在发送咨询...",
      success: "咨询已发送，我们的销售团队将尽快与您联系。",
      generic: "咨询提交失败，请稍后重试。",
      chooseProduct: "选择产品线",
      wasteDisabled: "请先选择产品线",
      wastePlaceholder: "选择废弃物类型",
      clear: "清除",
      all: "全选",
      empty: "请选择产品线以查看废弃物类型建议。",
      wasteTypes: {
        "PET bottles": "PET 瓶",
        "HDPE bottles": "HDPE 瓶",
        "PP plastics": "PP 塑料",
        "Mixed recyclable plastics": "混合可回收塑料",
        "Plastic film": "塑料薄膜",
        "Color-separated plastics": "按颜色分选的塑料",
        "Construction waste": "建筑废弃物",
        "Decoration waste": "装修废弃物",
        "Demolition waste": "拆除废弃物",
        "Bulky waste": "大件废弃物",
        "Light mixed waste": "轻质混合废弃物",
        "Recycled aggregate feed": "再生骨料原料",
      },
      resourceUnlock: {
        sending: "正在解锁资料...",
        generic: "暂时无法解锁资料，请稍后重试。",
        prefill: "我想领取更多 WEI LAN 资料。",
        errors: {
          INVALID_REQUEST: "请检查表单信息后重试。",
          INVALID_ORIGIN: "无法从当前页面解锁资料。",
          INVALID_RESOURCE: "该资料请求无效。",
          NAME_REQUIRED: "请输入姓名。",
          EMAIL_REQUIRED: "请输入工作邮箱。",
          EMAIL_INVALID: "请输入有效的工作邮箱。",
          COMPANY_REQUIRED: "请输入公司名称。",
          FIELD_TOO_LONG: "一个或多个字段内容过长。",
          DELIVERY_FAILED: "暂时无法解锁资料，请稍后重试。",
        },
      },
    },
  },
  "zh-Hant": {
    navigation: "主導覽",
    mobileNavigation: "行動版導覽",
    footerNavigation: "頁尾導覽",
    home: "首頁",
    about: "關於我們",
    products: "產品中心",
    solutions: "解決方案",
    service: "服務與支援",
    resources: "資源中心",
    contact: "聯絡我們",
    requestQuote: "索取報價",
    openNavigation: "開啟導覽",
    closeNavigation: "關閉導覽",
    language: "語言",
    productsOptical: "超級光選系統",
    productsConstruction: "營建及大型廢棄物處理線",
    caseStudies: "專案案例",
    processIntegration: "製程整合",
    supportModules: "支援模組",
    supportPath: "服務流程",
    workingMethod: "合作方式",
    buyerValue: "客戶價值",
    resourceLibrary: "資源庫",
    rfqPreparation: "詢價準備",
    teamUse: "團隊使用方式",
    faq: "常見問題",
    guideRoadmap: "指南規劃",
    companyFoundation: "企業基礎",
    capabilitySystem: "能力體系",
    credentials: "資格認證",
    evidenceGallery: "實績展示",
    news: "最新消息",
    projectConsultation: "專案諮詢",
    nextSteps: "後續流程",
    inquiryChecklist: "諮詢清單",
    socialNavigation: "社群媒體連結",
    followInstagram: "在 Instagram 關注 WEI LAN",
    followLinkedIn: "在 LinkedIn 關注 WEI LAN",
    followX: "在 X 關注 WEI LAN",
    followYouTube: "在 YouTube 關注 WEI LAN",
    organizationDescription: "專注於智慧廢棄物分選與資源回收系統的環保設備製造商。",
    contactFeedback: {
      PRODUCT_REQUIRED: "請選擇產品線。",
      NAME_REQUIRED: "請輸入姓名。",
      EMAIL_REQUIRED: "請輸入電子郵件。",
      EMAIL_INVALID: "請輸入有效的電子郵件地址。",
      MESSAGE_REQUIRED: "請輸入專案詳情。",
      FIELD_TOO_LONG: "一個或多個欄位內容過長。",
      INVALID_REQUEST: "請檢查表單資料後再試。",
      DELIVERY_FAILED: "暫時無法傳送諮詢，請稍後再試。",
      INTERNAL_ERROR: "諮詢提交失敗，請稍後再試。",
      sending: "正在傳送諮詢...",
      success: "諮詢已傳送，我們的銷售團隊將儘快與您聯絡。",
      generic: "諮詢提交失敗，請稍後再試。",
      chooseProduct: "選擇產品線",
      wasteDisabled: "請先選擇產品線",
      wastePlaceholder: "選擇廢棄物類型",
      clear: "清除",
      all: "全選",
      empty: "請選擇產品線以查看廢棄物類型建議。",
      wasteTypes: {
        "PET bottles": "PET 瓶",
        "HDPE bottles": "HDPE 瓶",
        "PP plastics": "PP 塑膠",
        "Mixed recyclable plastics": "混合可回收塑膠",
        "Plastic film": "塑膠薄膜",
        "Color-separated plastics": "按顏色分選的塑膠",
        "Construction waste": "營建廢棄物",
        "Decoration waste": "裝修廢棄物",
        "Demolition waste": "拆除廢棄物",
        "Bulky waste": "大型廢棄物",
        "Light mixed waste": "輕質混合廢棄物",
        "Recycled aggregate feed": "再生骨材原料",
      },
      resourceUnlock: {
        sending: "正在解鎖資源...",
        generic: "暫時無法解鎖資源，請稍後再試。",
        prefill: "我想索取更多 WEI LAN 資源資料。",
        errors: {
          INVALID_REQUEST: "請檢查表單資料後再試。",
          INVALID_ORIGIN: "無法從目前頁面解鎖資源。",
          INVALID_RESOURCE: "此資源請求無效。",
          NAME_REQUIRED: "請輸入姓名。",
          EMAIL_REQUIRED: "請輸入工作電子郵件。",
          EMAIL_INVALID: "請輸入有效的工作電子郵件。",
          COMPANY_REQUIRED: "請輸入公司名稱。",
          FIELD_TOO_LONG: "一個或多個欄位內容過長。",
          DELIVERY_FAILED: "暫時無法解鎖資源，請稍後再試。",
        },
      },
    },
  },
};
